
export const FETCH_GALLERY = 'FETCH_GALLERY'
export const REQUEST_GALLERY = 'REQUEST_GALLERY'
export const CHANGE_SWITCH="CHANGE_SWITCH"
export const CHANGE_VIEW="CHANGE_VIEW"
export const SHOW_LOADER="SHOW_LOADER"
export const HIDE_LOADER="HIDE_LOADER"
export const SHOW_ALERT="SHOW_ALERT"
export const HIDE_ALERT="HIDE_ALERT"
